[package]
name = "slides-radix-primitives-examples"
description = "Rust Radix Primitives examples."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_log.workspace = true
console_error_panic_hook.workspace = true
convert_case = "0.6.0"
radix-leptos-avatar = "0.0.2"
radix-leptos-checkbox = "0.0.2"
radix-leptos-icons = { git = "https://github.com/RustForWeb/radix", features = [
    "check",
    "font-italic",
] }
radix-leptos-label = "0.0.2"
radix-leptos-progress = "0.0.2"
radix-leptos-switch = "0.0.2"
radix-leptos-toggle = "0.0.2"
leptos = { version = "0.6.15", features = ["csr"] }
log.workspace = true
tailwind_fuse.workspace = true
