[package]
name = "slides-radix-primitives-examples"
description = "Rust Radix Primitives examples."
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
console_error_panic_hook.workspace = true
console_log.workspace = true
leptos = { version = "0.6.15", features = ["csr"] }
log.workspace = true
radix-leptos-avatar = "0.0.2"
radix-leptos-checkbox = "0.0.2"
radix-leptos-icons = "0.0.2"
radix-leptos-label = "0.0.2"
radix-leptos-progress = "0.0.2"
radix-leptos-switch = "0.0.2"
radix-leptos-toggle = "0.0.2"
